const isProd =
  process.env.NODE_ENV && process.env.NODE_ENV == "dev" ? false : true; //dont change manually
console.log("isProd", isProd);
// const isProd = true;
const localport = 3005;
let keys = {
  isProd: isProd,
  port: isProd ? 80 : localport,
  serverUrlBackend: "http://localhost:3004",
  serverUrlCurrent: isProd
    ? "https://backend.onechanneladmin.com"
    : `http://localhost:${localport}`,
  env: {
    allCollections: {
      mainDb: "MainDB",
      catalogs: "Catalogs",
      mainDBArchive: "MainDB_Archive",
      bundleKits: "BundleKits",
      fitment: "Fitment",
      reviews: "Reviews",
      amazonListing: "amazonListings",
      ebayListingsDB2: "ebayListingsDB2",
      marketplaceData: "marketplaceData",
      amazonfba: "amazonfba",
      channelAdminSettings: "ChannelAdminSettings",
      finalCatalogKeywords: "FinalCatalogKeywords",
      order: "order",
      ebayMultiSeller: "EbayMultiSeller",
      totalBrands: "TotalBrands",
      amazonMultiSeller: "amazonmultisellers",
      walmartSellers: "walmartsellers",
      meyerDb: "meyer_db",
      premierDb: "premier_db",
      subMainDb: "subMainDB",
      headerAttributes: "headerattributes",
      tasks: "Tasks",
      meta: "meta",
      AplusContent: "Apluscontent",
      productDataStatus: "productdataStatus",
      productData3: "productdata3",
      testMaindbChannel3: "testMaindbchannel3",
      permissionsOrganization: "permissionsOrganization",
      customTemplate: "custom_template",
      reportDetails: "reportdetails",
      amazonReport: "amazonreport",
      ebayCategories: "EbayCategories",
      walmartData: "walmarttest2",
      transactions: "transactions",
      returnedOrders: "returnedOrders",
      amazonAsin2: "amazonasin2",
      shipmentDetails: "ShipmentDetails",
      mapPrices: "Mapprices",
      googleMeets: "GoogleMeets",
      customers: "Customers",
      apolloContacts: "ApolloContacts",
      payOuts: "PayOuts",
      ebayCompatibility: "ebaycompatibility",
      ebaySettings: "ebaySettings",
      purchaseOrders: "PurchaseOrders",
      discountCampaigns: "DiscountCampaigns",
      wareHouseDetails: "WareHouseDetails",
      wmsInventory: "WMSInventory",
      inventoryHistory: "InventoryHistory",
      stripeProducts: "stripeProducts",
      campaigns: "Campaigns",
      freshworksDB: "freshWorks",
      repricerDB: "RepricerDB",
      salesCrm: "Sales-CRM",
      shipmentDetails: "ShipmentDetails",
      apluscontent: "Apluscontent",
      amazonfba: "amazonfba",
      fbaShipments: "fbaShipments",
      fitmentShopify: "FitmentShopify",
      claims: "claims",
      crmTasks: "crmTasks",
      creditsHistory: "creditsHistory",
      cache: "cache",
      sellerHistory: "sellerHistory",
      globalQueue: "globalQueue",
      metaPosts: "metaPosts",
      marketing: "marketing",
      workFlows: "workFlows",
      newdashboard: "newdashboard",
    },
  }
};

module.exports = { ...keys };
